### ISSUE TITLE
Name IDBArrayKey not found

### ISSUE THREAD

**Issue by jvllmr** [piotr-cz/redux-persist-idb-storage#12]
https://github.com/piotr-cz/redux-persist-idb-storage/blob/b703cc9c6c6178b81d51a7192b67fd7a13748fb2/src/index.ts#L63

The Type was used here but got removed already. A new Release would fix this issue for me.

**Comment by piotr-cz** [comment]
Can you please confirm that https://github.com/piotr-cz/redux-persist-idb-storage/commit/7548b176e8cb5a57f62008bcd1d9b7735d985018 fixes the issue?

**Comment by jvllmr** [comment]
Replacing the Type Union with `any` works for me (I tested it).

**Comment by piotr-cz** [comment]
Thanks, I've released [v1.1.3](https://github.com/piotr-cz/redux-persist-idb-storage/releases/tag/v1.1.3) version with fixes to types

**Comment by jvllmr** [comment]
Great 👍
