### ISSUE TITLE
Error restoring data [object Object]

### ISSUE THREAD

**Issue by piotr-cz** [piotr-cz/redux-persist-idb-storage#16]
Reported by @bigfree:

I try, build is success but now there is an error in retrieving data from the DB 😢 
```text
redux-persist/getStoredState: Error restoring data [object Object] SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at defaultDeserialize (getStoredState.js:39:1)
    at getStoredState.js:23:1
```
The data is stored in the database, but when the page is refreshed, it is no longer in the database. However, the structure of the database remains the same.

**Store data:**
![image](https://user-images.githubusercontent.com/3304725/173056009-4dfffb27-6a00-4dcb-84b8-ece23869d78c.png)

**After refresh:**
![image](https://user-images.githubusercontent.com/3304725/173056150-de2f8206-bea2-456c-b50c-1c8b6c4b38d7.png)

My persist config:
```ts
const persistConfig: PersistConfig<any> = {
    key: 'root',
    version: 1,
    storage: createIdbStorage({
        name: 'craedit',
        storeName: 'craeditstore',
        version: 1
    }),
    timeout: 100,
    serialize: false,
    debug: true,
    blacklist: ['point']
};
```

_Originally posted by @bigfree in https://github.com/piotr-cz/redux-persist-idb-storage/issues/14#issuecomment-1152265740_

**Comment by piotr-cz** [comment]
@bigfree
Please try with

- using `serialize: false, deserialize: false`

  ```diff
  const persistConfig = {
    key: 'root',
    storage: createIdbStorage({name: 'myApp', storeName: 'keyval'}),
    serialize: false,
  +  deserialize: false,
  }
  ```

- removing `serialize: false` option

  ```diff
  const persistConfig = {
    key: 'root',
    storage: createIdbStorage({name: 'myApp', storeName: 'keyval'}),
  -  serialize: false,
  }
  ```

and let me know if that fixed the issue.

Explaination:
since [redux-persist@6.0.0](https://github.com/rt2zz/redux-persist/commit/a94f291397592cf29376e6e22e101e36d66daff0) the new undocumented `deserialize` option seem to be have set to same value as `serialize`.
So both should be set either to *false* or *true*.

**Comment by bigfree** [comment]
@piotr-cz
Cool, looks like it works!
But I had to extend **PersistConfig** type because it doesn't contain deserialize value..

```ts
const persistConfig: PersistConfig<any> & {deserialize: boolean} = {
   ...
}
```

> Explaination:
since [redux-persist@6.0.0](https://github.com/rt2zz/redux-persist/commit/a94f291397592cf29376e6e22e101e36d66daff0) the new undocumented deserialize option seem to be have set to same value as serialize.
So both should be set either to false or true.

ah good to know 😄

**Comment by piotr-cz** [comment]
Did you try with setting both serialize & deserialize option to *true* and *false*?
I'd like to document that in README.

Too bad authors didn't [document this](https://github.com/rt2zz/redux-persist/releases) as IMHO it's a breaking change.

As for types, there are two PR's: https://github.com/rt2zz/redux-persist/pull/1153, https://github.com/rt2zz/redux-persist/pull/1304

**Comment by bigfree** [comment]
This only works if both values are set to **true/false**. 
```ts
serialize: true,
deserialize: true,
```

```ts
serialize: false,
deserialize: false,
```

if option to serialize is set, of course object is not stored in database, only string. 
Thank for your time and solved problem
