### ISSUE TITLE
`getAll` doesn't need a `readwrite` lock

### ISSUE THREAD

**Issue by tony-scio** [piotr-cz/redux-persist-idb-storage#5]
`getAll` can be `readonly` here:
https://github.com/piotr-cz/redux-persist-idb-storage/blob/master/src/index.ts#L112

I would have PR'd just this fix, but I ended up forking away from the library because I wanted `idb` v6 and didn't think that'd be accepted because the v3 dep is considered a feature in the readme. Anyway, here's my v6 impl which inherently fixes the above. I'm happy to PR it if you like.

```ts
/**
 * Thin wrapper around idb to use as redux-persist storage using single object store for all data
 * @see https://github.com/jakearchibald/idb
 *
 * Based on https://github.com/piotr-cz/redux-persist-idb-storage, but upgraded to idb 6
 * and fixed a perf bug.
 */
import { openDB } from 'idb'

interface Options {
  name: string
  storeName: string
  version: number
}

const defaultOptions: Options = {
  name: 'keyval-store',
  storeName: 'keyval',
  version: 1
}

export default function createIdbStorage (options: Options = defaultOptions) {
  const dbPromise = openDB(options.name, options.version, {
    upgrade (db) {
      db.createObjectStore(options.storeName)
    }
  })

  return {
    async getItem (key: string) {
      return (await dbPromise).get(options.storeName, key)
    },

    async setItem (key: string, item: IDBValidKey) {
      return (await dbPromise).put(options.storeName, item, key)
    },

    async removeItem (key: string) {
      return (await dbPromise).delete(options.storeName, key)
    },

    async getAllKeys () {
      return (await dbPromise).getAllKeys(options.storeName)
    },

    async getAll () {
      return (await dbPromise).getAll(options.storeName)
    },

    async clear () {
      return (await dbPromise).clear(options.storeName)
    }
  }
}
```

**Comment by piotr-cz** [comment]
Thank you 👍  it's fixed in https://github.com/piotr-cz/redux-persist-idb-storage/commit/9a80a5419d5470822e694005a165c537c1cbaec1 and released in [v1.1.2](https://github.com/piotr-cz/redux-persist-idb-storage/releases/tag/v1.1.2).

As for `idb v6`, I was thinking about releasing new version with latest `idb` dependency as v2 - now that IE support is dropped.
However I'm not using Redux anymore and I would not be able to test it properly.

If you want, go ahead with PR
