### ISSUE TITLE
Any recommendations for use with NextJS

### ISSUE THREAD

**Issue by shauntrennery** [piotr-cz/redux-persist-idb-storage#9]
`Error storing data IDB requires a browser environment` logged to the terminal on startup. Are there any recommendations for use within a NextJS SSR app?

**Comment by piotr-cz** [comment]
Package could be wrapped in function that would check if indexedDB is available and in case that it isn't - use in-memory storage.

Or maybe better: aforementioned logic could be done in store which would select appropriate adapter.
What do you think?

**Comment by piotr-cz** [comment]
What about checking for indexedDB in store?

```js
const persistConfig = {
  key: 'root',
  storage: globalThis.indexedDB ? createIdbStorage({name: 'myApp', storeName: 'keyval'}) : undefined,
  serialize: false, 
}
```

**Comment by shauntrennery** [comment]
@piotr-cz I really appreciate the help. I followed your advice and have changed the way I create the store depending on the environment. It's working as expected. We have a large store and persisting it to IndexedDB rather than localstorage is a much better solution.

**Comment by piotr-cz** [comment]
Did you use my example or used other code to check for an environment?
I'm asking because I'd like to add a note about SSR handling to repo readme.

You can also submit PR with instructions yourself 😃

**Comment by shauntrennery** [comment]
@piotr-cz I used `const isClient = typeof window !== 'undefined';`

and then 

```
import storage from 'redux-persist/lib/storage';
import createIdbStorage from '@piotr-cz/redux-persist-idb-storage';

const persistConfig = {
  key: 'root',
  storage: isClient ? createIdbStorage({ name: 'DB', storeName: 'Web' }) : storage,
  whitelist: ['app', 'auth']
};
```

**Comment by piotr-cz** [comment]
Thanks, would you mind checking if checking for `globalThis.indexedDB` has similar effect?
I'd prefer to use feature detection as a recommendation in readme.

By the way - In case that local storage is not available, redux-persist uses [noop](https://github.com/rt2zz/redux-persist/blob/d7efde9115a0bd2d6a0309ac6fb1c018bf06dc30/src/storage/getStorage.js#L42) functions instead.

**Comment by shauntrennery** [comment]
@piotr-cz I've applied your `cleaner` solution and all is working as expected. Thanks.

**Comment by piotr-cz** [comment]
Thanks 👍 
I've just updated setup instructions: https://github.com/piotr-cz/redux-persist-idb-storage/commit/0424b44679a9721e5ff391ad3c071c8c55cbd303
